fix von_generate_transactions args, add error handling

diff --git a/bin/von_generate_transactions b/bin/von_generate_transactions
--- a/bin/von_generate_transactions
+++ b/bin/von_generate_transactions
@@ -6,7 +6,7 @@ usage () {
     echo "Example: $0 -i x.x.x.x -n y";
 }
 
-options='in:h'
+options=':i:n:h'
 while getopts $options option
 do
     case $option in
@@ -28,6 +28,11 @@ fi
 # If we don't explicitely set IP, then discover nodes internally
 if [ -z "$IP" ]; then
     # Nodes discover each other internally
+    if [ -z "$IP1" ] || [ -z "$IP2" ] || [ -z "$IP3" ] || [ -z "$IP4" ]; then
+        echo "Cannot discover node ips. Are the nodes running?"
+        exit 1
+    fi
+    
     IP1="$(getent hosts node1 | awk '{ print $1 }')"
     IP2="$(getent hosts node2 | awk '{ print $1 }')"
     IP3="$(getent hosts node3 | awk '{ print $1 }')"
