Add support for backup and restore.
Signed-off-by: Wade Barnes <wade@neoterictech.ca>

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -1,7 +1,6 @@
 #!/bin/bash
 export MSYS_NO_PATHCONV=1
 export DOCKERHOST=${APPLICATION_URL-$(docker run --rm --net=host eclipse/che-ip)}
-set -e
 
 SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"
 export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-von}"
@@ -9,6 +8,8 @@ export DEFAULT_CLI_SCRIPT_DIR='./cli-scripts'
 
 export LEDGER_TIMEOUT="${LEDGER_TIMEOUT:-60}"
 export LEDGER_URL_CONFIG="${LEDGER_URL_CONFIG}"
+
+export ROOT_BACKUP_DIR=backup
 
 # Running on Windows?
 if [[ "$OSTYPE" == "msys" ]]; then
@@ -64,14 +65,34 @@ usage () {
   generateSecrets - Generate a random set of secrets using openssl; a Seed and a Key.
 
   indy-cli - Run Indy-Cli commands in a Indy-Cli container environment.
- 
+
         $0 indy-cli -h
           - Display specific help documentation.
 
   cli - Run a command in an Indy-Cli container.
-        
+
         $0 cli -h
           - Display specific help documentation.
+
+  backup [description] - Backup the current von-network environment.
+          Creates a set of tar.gz archives of each of the environment's volumes.
+          Backup sets are stored in a ./backup/date/time folder structure.
+
+          Examples:
+          $0 backup
+          $0 backup "The description of my environment's current state."
+            - Make a backup and include the description in a ReadMe.txt file.
+
+  restore [filter] - Restore a given backup set.  Defaults to restoring the most recent backup.
+          Examples:
+          $0 restore
+            - Restore the most recent backup.
+          $0 restore 13-15-37
+            - Restore the backup from 13-15-37 today.
+          $0 restore von_client-data_2021-08-23_08-21-08.tar
+            - Restore the backup set containing the von_client-data_2021-08-23_08-21-08.tar archive.
+          $0 restore 2021-08-23
+            - Restore the most recent backup set from 2021-08-23.
 EOF
 exit 1
 }
@@ -79,20 +100,20 @@ exit 1
 indyCliUsage () {
   cat <<-EOF
 
-  Usage: 
+  Usage:
     $0 [options] indy-cli [-h] [command] [parameters]
-    
+
     Run Indy-Cli commands in a Indy-Cli container environment.
       - Refer to the cli-scripts directory for available scripts and their parameters.
       - Refer to './docs/Writing Transactions to a Ledger for an Un-privileged Author.md' for
         additional examples.
-      
+
     Options:
       -v <FullyQualifiedPathToScripts/>
         - Mount a script volume to the container.  By default the 'cli-scripts' directory is mounted to the container.
 
     Examples:
-    
+
     $0 indy-cli
       - Start an interactive indy-cli session in your Indy-Cli Container.
 
@@ -107,15 +128,15 @@ cliUsage () {
 
   Usage:
     $0 [options] cli [-h] [command]
-    
+
     Run a command in an Indy-Cli container.
 
     Options:
       -v <FullyQualifiedPathToScripts/>
         - Mount a script volume to the container.  By default the 'cli-scripts' directory is mounted to the container.
-    
+
     Examples:
-    
+
     $0 cli reset
       - Reset your Indy-CLI container's environment
 
@@ -207,7 +228,7 @@ function initEnv() {
 
   IP=""
   IPS=""
-  if [ ! -z $(echo ${1} | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}') ]; then 
+  if [ ! -z $(echo ${1} | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}') ]; then
     if [[ $1 == *","* ]]; then
       IPS="$1"
     else
@@ -221,7 +242,7 @@ function initEnv() {
 }
 
 function runCliCommand() {
-  
+
   unset displayCliUsage
   for arg in "$@"; do
     # Remove recognized arguments from the list after processing.
@@ -270,7 +291,7 @@ function runCliCommand() {
 
   # Need to escape quotes and commas so they don't get removed along the way ...
   escapedArgs=$(echo $@ | sed "s~'~\\\'~g" | sed 's~\"~\\"~g')
-  
+
   # Quote the escaped args so docker-compose does not try to perform any processing on them ...
   # Separate the command and the args so they don't get treated as one argument by the scripts in the container ...
   cmd+="
@@ -288,7 +309,7 @@ function logs() {
     while getopts ":f-:" FLAG; do
       case $FLAG in
         f ) local _force=1 ;;
-        - ) 
+        - )
             case ${OPTARG} in
                 "no-tail"*) no_tail=1
               ;;
@@ -347,7 +368,7 @@ function wait_for_ledger() {
 function install_taa() {
   (
     # if flag is set, copy the sample config/sample_aml.json and config/sample_taa.json
-    # to config/aml.json and config/taa.json. Also create a marker file so that we 
+    # to config/aml.json and config/taa.json. Also create a marker file so that we
     # clean up on shutdown and still support backward compatibility where people previously
     # their own custom versions and don't want them removed.
     local rtnCd=0
@@ -361,7 +382,7 @@ function install_taa() {
 
 function remove_taa() {
   (
-    # if the marker exists indicating we created the aml and taa files, make sure we remove them to clean up. 
+    # if the marker exists indicating we created the aml and taa files, make sure we remove them to clean up.
     if [ -f "./config/.samples.used" ]; then
       rm -f ./config/aml.json ./config/taa.json ./config/.samples.used
     fi
@@ -391,6 +412,138 @@ function generateSecrets() {
   echo "Seed: $(generateSeed)"
   echo "Key: $(generateKey)"
   echo
+}
+
+function backup() {
+  (
+    _msg=$@
+
+    volumes=$(docker -l ERROR compose config --volumes)
+    timeStamp=`date +\%Y-\%m-\%d_%H-%M-%S`
+    datePart=${timeStamp%%_*}
+    timePart=${timeStamp#*_}
+    backupDir=${ROOT_BACKUP_DIR}/${datePart}/${timePart}
+    backupVolumeMount=$(getVolumeMount ./${ROOT_BACKUP_DIR})/
+    mkdir -p ./${backupDir}
+    if [ ! -z "${_msg}" ]; then
+      echo "${_msg}" > ./${backupDir}/ReadMe.txt
+    fi
+
+    for volume in ${volumes}; do
+      sourceVolume=${COMPOSE_PROJECT_NAME}_${volume}
+      archiveName=${sourceVolume}_${timeStamp}.tar.gz
+      archivePath="/${backupDir}/${archiveName}"
+
+      echoYellow \\n"Backing up ${sourceVolume} to ${archivePath} ..."
+      docker run \
+        --rm \
+        --name von-network-backup \
+        -v ${backupVolumeMount}:/${ROOT_BACKUP_DIR} \
+        -v ${sourceVolume}:/source_volume von-network-base \
+        tar -czvf ${archivePath} -C /source_volume/ .
+    done
+  )
+}
+
+function restore() {
+  (
+    _fileName=${1}
+    archivePath=$(findBackup ${1})
+    archiveDirectory=${archivePath%/*}
+
+    datePart=$(echo ${archivePath} | awk -F_ '{print $3}')
+    timePart=$(echo ${archivePath} | awk -F_ '{print $4}')
+    archiveSuffix="${datePart}_${timePart}"
+    timePart=${timePart%%.*}
+    backupVolumeMount=$(getVolumeMount ./${ROOT_BACKUP_DIR})/
+
+    if promptForConfirmation "You are about to restore from the '${archiveDirectory}' backup set.\nYour existing data will be lost if not backed up first."; then
+
+      deleteVolumes
+      volumes=$(docker -l ERROR compose config --volumes)
+      for volume in ${volumes}; do
+        targetVolume=${COMPOSE_PROJECT_NAME}_${volume}
+        archiveName=${targetVolume}_${archiveSuffix}
+        archivePath="/${archiveDirectory}/${archiveName}"
+
+        echoYellow \\n"Restoring ${targetVolume} from ${archivePath} ..."
+        docker run \
+          --rm \
+          --name von-network-restore \
+          --user root \
+          -v ${backupVolumeMount}:/${ROOT_BACKUP_DIR} \
+          -v ${targetVolume}:/target_volume von-network-base \
+          tar --same-owner -xzvpf ${archivePath} -C /target_volume/
+      done
+    else
+      echo -e \\n"Restore aborted."
+    fi
+  )
+}
+
+function findBackup(){
+  (
+    _fileName=${1}
+
+    # If no backup file was specified, find the most recent set.
+    # Otherwise treat the value provided as a filter to find the most recent backup set matching the filter.
+    if [ -z "${_fileName}" ]; then
+      _fileName=$(find ${ROOT_BACKUP_DIR}* -type f -printf '%T@ %p\n' | grep .tar.gz | sort | tail -n 1 | sed 's~^.* \(.*$\)~\1~')
+    else
+      _fileName=$(find ${ROOT_BACKUP_DIR}* -type f -printf '%T@ %p\n' | grep .tar.gz | grep ${_fileName} | sort | tail -n 1 | sed 's~^.* \(.*$\)~\1~')
+    fi
+
+    echo "${_fileName}"
+  )
+}
+
+function echoYellow (){
+  (
+  _msg=${1}
+  _yellow='\e[33m'
+  _nc='\e[0m' # No Color
+  echo -e "${_yellow}${_msg}${_nc}" >&2
+  )
+}
+
+function promptForConfirmation(){
+  (
+    _msg=${@}
+    echoYellow "\n${_msg}"
+    read -n1 -s -r -p $'\e[33mWould you like to continue?\e[0m  Press \'Y\' to continue, or any other key to exit ...\n' key
+    if [[ $(toLower ${key}) == 'y' ]]; then
+      return 0
+    else
+      return 1
+    fi
+  )
+}
+
+function deleteVolumes() {
+  (
+    _projectName=${COMPOSE_PROJECT_NAME:-docker}
+
+    echoYellow \\n"Stopping and removing any running containers ..."
+    docker -l ERROR compose down -v
+
+    _pattern="^${_projectName}_\|^docker_"
+    _volumes=$(docker volume ls -q | grep ${_pattern})
+    if [ ! -z "${_volumes}" ]; then
+      echoYellow "Removing project volumes ..."
+      echo ${_volumes} | xargs docker volume rm
+    fi
+  )
+}
+
+function getVolumeMount() {
+  path=${1}
+  path=$(realpath ${path})
+  path=${path%%+(/)}
+  if [[ "$OSTYPE" == "msys" ]]; then
+    # When running on Windows, you need to prefix the path with an extra '/'
+    path="/${path}"
+  fi
+  echo ${path}
 }
 # =================================================================================================================
 
@@ -454,9 +607,7 @@ case "${COMMAND}" in
     ;;
   down|rm)
       initEnv "$@"
-      docker-compose \
-        --log-level ERROR down \
-        -v
+      deleteVolumes
       remove_taa
     ;;
   build)
@@ -470,6 +621,13 @@ case "${COMMAND}" in
     ;;
   generatesecrets)
       generateSecrets
+    ;;
+
+  backup)
+      backup "$@"
+    ;;
+  restore)
+      restore $@
     ;;
   *)
       usage;;
